"""Phase 4: Revenue Optimizer — ROI-driven task routing and worker improvement.

Analyzes which workers/models generate the most revenue per cost,
then adjusts Manager routing priorities to maximize ROI.

Reference: GenericAgent agentmain.py next_llm() — runtime model rotation
"""

from __future__ import annotations

import logging
import sqlite3
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class ROIReport:
    """Return-on-investment analysis for workers and models."""
    worker_roi: dict[str, float]  # worker_type → ROI ratio
    model_cost_efficiency: dict[str, float]  # model → tasks_per_yuan
    best_worker: str
    best_model: str
    recommendations: list[str]
    total_cost: float
    total_estimated_revenue: float
    overall_roi: float


class RevenueOptimizer:
    """ROI-driven optimization engine.

    Tracks revenue per task → calculates ROI per worker/model →
    generates routing priority adjustments.

    Usage:
        opt = RevenueOptimizer(manager)
        opt.record_revenue(task_id, revenue_yuan)
        report = opt.analyze()
        opt.apply_optimizations(report)
    """

    def __init__(
        self,
        db_path: str = "c:/Users/25454/业务中控台/ama/data/ama.db",
    ):
        self.db_path = Path(db_path)
        self._init_db()

    def _init_db(self) -> None:
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS revenue_records (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    task_id TEXT NOT NULL,
                    worker_type TEXT NOT NULL,
                    model TEXT NOT NULL,
                    cost_yuan REAL DEFAULT 0.0,
                    revenue_yuan REAL DEFAULT 0.0,
                    timestamp TEXT NOT NULL
                )
            """)
            conn.commit()

    def record_revenue(
        self, task_id: str, worker_type: str, model: str,
        cost_yuan: float, revenue_yuan: float,
    ) -> None:
        """Record revenue generated by a task."""
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.execute(
                """INSERT INTO revenue_records
                   (task_id, worker_type, model, cost_yuan, revenue_yuan, timestamp)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (task_id, worker_type, model, cost_yuan, revenue_yuan,
                 datetime.now().isoformat()),
            )
            conn.commit()

    def analyze(self, window_days: int = 7) -> ROIReport:
        """Analyze ROI across workers and models."""
        cutoff = (datetime.now() - timedelta(days=window_days)).isoformat()

        with sqlite3.connect(str(self.db_path)) as conn:
            # By worker
            worker_rows = conn.execute(
                """SELECT worker_type,
                          SUM(cost_yuan), SUM(revenue_yuan), COUNT(*)
                   FROM revenue_records
                   WHERE timestamp >= ?
                   GROUP BY worker_type""",
                (cutoff,),
            ).fetchall()

            # By model
            model_rows = conn.execute(
                """SELECT model,
                          SUM(cost_yuan), SUM(revenue_yuan), COUNT(*)
                   FROM revenue_records
                   WHERE timestamp >= ?
                   GROUP BY model""",
                (cutoff,),
            ).fetchall()

        # Calculate ROI per worker
        worker_roi = {}
        total_cost = 0.0
        total_revenue = 0.0
        for w_type, cost, revenue, tasks in worker_rows:
            cost = cost or 0
            revenue = revenue or 0
            roi = revenue / max(cost, 0.001)  # avoid div by zero
            worker_roi[w_type] = round(roi, 2)
            total_cost += cost
            total_revenue += revenue

        # Calculate cost efficiency per model
        model_efficiency = {}
        for model, cost, revenue, tasks in model_rows:
            cost = cost or 0
            tasks_count = tasks or 1
            model_efficiency[model] = round(tasks_count / max(cost, 0.001), 2)

        # Best performers
        best_worker = max(worker_roi, key=worker_roi.get) if worker_roi else "none"
        best_model = max(model_efficiency, key=model_efficiency.get) if model_efficiency else "none"

        # Generate recommendations
        recommendations = []
        if worker_roi:
            worst = min(worker_roi, key=worker_roi.get)
            if worker_roi[worst] < 1.0:
                recommendations.append(
                    f"Worker '{worst}' has ROI < 1 (cost > revenue). "
                    f"Consider disabling or using cheaper model."
                )
        if model_efficiency:
            worst_model = min(model_efficiency, key=model_efficiency.get)
            best_model_name = max(model_efficiency, key=model_efficiency.get)
            if model_efficiency[worst_model] < model_efficiency[best_model_name] * 0.5:
                recommendations.append(
                    f"Model '{worst_model}' is {model_efficiency[best_model_name] / max(model_efficiency[worst_model], 0.01):.0f}x "
                    f"less efficient than '{best_model_name}'. Increase weight of efficient model."
                )
        if total_revenue > 0 and total_cost / total_revenue > 0.3:
            recommendations.append(
                f"Cost is {total_cost/total_revenue*100:.0f}% of revenue. "
                f"Optimize by routing more tasks to local/free models."
            )

        overall_roi = total_revenue / max(total_cost, 0.001)

        return ROIReport(
            worker_roi=worker_roi,
            model_cost_efficiency=model_efficiency,
            best_worker=best_worker,
            best_model=best_model,
            recommendations=recommendations,
            total_cost=round(total_cost, 4),
            total_estimated_revenue=round(total_revenue, 2),
            overall_roi=round(overall_roi, 2),
        )

    def suggest_routing_adjustments(self, report: ROIReport) -> dict[str, Any]:
        """Convert ROI analysis into concrete routing adjustments.

        Returns config changes that can be applied to ModelRouter weights.
        """
        adjustments = {}
        for model, efficiency in report.model_cost_efficiency.items():
            if efficiency > 10:
                adjustments[model] = {"action": "increase_weight", "by": 2}
            elif efficiency < 1:
                adjustments[model] = {"action": "decrease_weight", "by": 0.5}

        return {
            "model_weight_adjustments": adjustments,
            "prefer_worker": report.best_worker,
            "prefer_model": report.best_model,
            "recommendations": report.recommendations,
        }
